import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { db } from "@/db/database";
import { getSymptomById } from "@/db/symptoms";
import { getAllLogs } from "@/db/queries";
import type { CustomSymptom } from "@/types";

export async function exportToPdf(
  startMs?: number,
  endMs?: number
): Promise<void> {
  const now = Date.now();
  const start = startMs ?? now - 30 * 24 * 60 * 60 * 1000;
  const end = endMs ?? now;

  const allLogs = await getAllLogs();
  const customSymptoms: CustomSymptom[] = await db.customSymptoms.toArray();
  const logs = allLogs
    .filter((l) => l.timestamp >= start && l.timestamp <= end)
    .sort((a, b) => a.timestamp - b.timestamp);

  function resolveName(id: string): string {
    const catalog = getSymptomById(id);
    if (catalog) return catalog.name;
    const custom = customSymptoms.find((s) => s.id === id);
    if (custom) return custom.name;
    return id;
  }

  if (logs.length === 0) {
    alert("No logs found for this period.");
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // --- CONFIDENTIAL HEADER (every page helper) ---
  function addPageHeaders(pageDoc: jsPDF) {
    const totalPages = pageDoc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pageDoc.setPage(i);

      // Confidential banner at top
      pageDoc.setFillColor(220, 20, 60);
      pageDoc.rect(0, 0, pageWidth, 8, "F");
      pageDoc.setFontSize(7);
      pageDoc.setFont("helvetica", "bold");
      pageDoc.setTextColor(255, 255, 255);
      pageDoc.text(
        "CONFIDENTIAL — PERSONAL HEALTH INFORMATION — NOT FOR UNAUTHORIZED DISTRIBUTION",
        pageWidth / 2,
        5.5,
        { align: "center" }
      );

      // Footer
      pageDoc.setFontSize(7);
      pageDoc.setFont("helvetica", "normal");
      pageDoc.setTextColor(128, 128, 128);
      pageDoc.text(
        "This document contains personal health information. Keep secure. Share only with healthcare providers.",
        pageWidth / 2,
        pageHeight - 14,
        { align: "center" }
      );
      pageDoc.text(
        `Generated by PostOpp — Page ${i} of ${totalPages} — ${formatDate(new Date())}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );

      // Reset text color
      pageDoc.setTextColor(0, 0, 0);
    }
  }

  // --- PAGE 1: Summary ---
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 46);
  doc.text("PostOpp Symptom Report", 20, 18);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(
    `${formatDate(new Date(start))} — ${formatDate(new Date(end))}`,
    20,
    26
  );
  doc.text(`Total entries: ${logs.length}`, 20, 32);

  // Medical disclaimer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "PostOpp is a personal symptom tracker. This report is NOT a medical diagnosis. Consult your healthcare provider.",
    20,
    38
  );

  // Summary table
  const summaryMap = new Map<
    string,
    { count: number; total: number; min: number; max: number }
  >();
  for (const log of logs) {
    const existing = summaryMap.get(log.symptomId);
    if (existing) {
      existing.count++;
      existing.total += log.painLevel;
      existing.min = Math.min(existing.min, log.painLevel);
      existing.max = Math.max(existing.max, log.painLevel);
    } else {
      summaryMap.set(log.symptomId, {
        count: 1,
        total: log.painLevel,
        min: log.painLevel,
        max: log.painLevel,
      });
    }
  }

  const summaryRows = Array.from(summaryMap.entries()).map(
    ([id, stats]) => {
      return [
        resolveName(id),
        String(stats.count),
        (stats.total / stats.count).toFixed(1),
        String(stats.min),
        String(stats.max),
      ];
    }
  );

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 20, 46);

  autoTable(doc, {
    startY: 50,
    head: [["Symptom", "Count", "Avg Pain", "Min", "Max"]],
    body: summaryRows,
    theme: "grid",
    headStyles: { fillColor: [26, 26, 46] },
    styles: { fontSize: 10 },
  });

  // --- PAGE 2+: Detailed Log ---
  doc.addPage();
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(26, 26, 46);
  doc.text("Detailed Log", 20, 18);

  const detailRows = logs.map((log) => {
    const date = new Date(log.timestamp);
    return [
      formatDate(date),
      formatTime(date),
      resolveName(log.symptomId),
      `${log.painLevel}/10`,
      log.followUpPainLevel !== null ? `${log.followUpPainLevel}/10` : "—",
      log.latitude !== null
        ? `${log.latitude.toFixed(4)}, ${log.longitude!.toFixed(4)}`
        : "—",
    ];
  });

  autoTable(doc, {
    startY: 24,
    head: [["Date", "Time", "Symptom", "Level", "Follow-up", "GPS Location"]],
    body: detailRows,
    theme: "grid",
    headStyles: { fillColor: [26, 26, 46] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 20 },
      5: { cellWidth: 35 },
    },
  });

  // Apply headers/footers to all pages
  addPageHeaders(doc);

  // Log export time
  try {
    await db.settings.update(1, { lastExportDate: Date.now() });
  } catch {}

  doc.save(`postopp-report-${formatDateFile(new Date())}.pdf`);
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatTime(d: Date): string {
  return d.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });
}

function formatDateFile(d: Date): string {
  return d.toISOString().slice(0, 10);
}
