import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { db } from "@/db/database";
import { getSymptomById } from "@/db/symptoms";
import { getPainColor } from "./constants";

export async function exportToPdf(
  startMs?: number,
  endMs?: number
): Promise<void> {
  const now = Date.now();
  const start = startMs ?? now - 30 * 24 * 60 * 60 * 1000; // default last 30 days
  const end = endMs ?? now;

  const logs = await db.logs
    .where("timestamp")
    .between(start, end)
    .toArray();
  logs.sort((a, b) => a.timestamp - b.timestamp);

  if (logs.length === 0) {
    alert("No logs found for this period.");
    return;
  }

  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("PostOpp Symptom Report", 20, 20);

  // Date range
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(
    `${formatDate(new Date(start))} — ${formatDate(new Date(end))}`,
    20,
    28
  );
  doc.text(`Total entries: ${logs.length}`, 20, 34);

  // Summary table
  const summaryMap = new Map<
    string,
    { count: number; total: number; min: number; max: number }
  >();
  for (const log of logs) {
    const existing = summaryMap.get(log.symptomId);
    if (existing) {
      existing.count++;
      existing.total += log.painLevel;
      existing.min = Math.min(existing.min, log.painLevel);
      existing.max = Math.max(existing.max, log.painLevel);
    } else {
      summaryMap.set(log.symptomId, {
        count: 1,
        total: log.painLevel,
        min: log.painLevel,
        max: log.painLevel,
      });
    }
  }

  const summaryRows = Array.from(summaryMap.entries()).map(
    ([id, stats]) => {
      const symptom = getSymptomById(id);
      return [
        symptom?.name ?? id,
        String(stats.count),
        (stats.total / stats.count).toFixed(1),
        String(stats.min),
        String(stats.max),
      ];
    }
  );

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 20, 44);

  autoTable(doc, {
    startY: 48,
    head: [["Symptom", "Count", "Avg Pain", "Min", "Max"]],
    body: summaryRows,
    theme: "grid",
    headStyles: { fillColor: [26, 26, 46] },
    styles: { fontSize: 10 },
  });

  // Detail table
  doc.addPage();
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Detailed Log", 20, 20);

  const detailRows = logs.map((log) => {
    const symptom = getSymptomById(log.symptomId);
    const date = new Date(log.timestamp);
    return [
      formatDate(date),
      formatTime(date),
      symptom?.name ?? log.symptomId,
      `${log.painLevel}/10`,
      log.followUpPainLevel !== null ? `${log.followUpPainLevel}/10` : "—",
      log.latitude !== null
        ? `${log.latitude.toFixed(4)}, ${log.longitude!.toFixed(4)}`
        : "—",
    ];
  });

  autoTable(doc, {
    startY: 26,
    head: [["Date", "Time", "Symptom", "Level", "Follow-up", "Location"]],
    body: detailRows,
    theme: "grid",
    headStyles: { fillColor: [26, 26, 46] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 25 },
      1: { cellWidth: 20 },
      5: { cellWidth: 35 },
    },
  });

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by PostOpp — Page ${i} of ${pageCount}`,
      20,
      doc.internal.pageSize.height - 10
    );
  }

  doc.save(`postopp-report-${formatDateFile(new Date())}.pdf`);
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function formatTime(d: Date): string {
  return d.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });
}

function formatDateFile(d: Date): string {
  return d.toISOString().slice(0, 10);
}
